sudo: enabled

language: python
python:
    - "3.6"

install:
    - pip install -r requirements.txt

script:
    # - python ./movie_ui/manage.py test
    - coverage run --source='./movie' manage.py test --traceback --debug-mode

