# Generated by Django 2.1.5 on 2019-02-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('release_date', models.DateField()),
                ('runtime', models.PositiveSmallIntegerField()),
                ('poster_path', models.CharField(max_length=256)),
                ('overview', models.TextField()),
                ('imdb_id', models.CharField(max_length=256)),
                ('imdb_rating', models.FloatField()),
                ('homepage', models.CharField(max_length=256)),
                ('preview', models.CharField(max_length=256)),
                ('genres', models.ManyToManyField(to='movie.Genre')),
            ],
        ),
    ]
