# Generated by Django 2.1.5 on 2019-02-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='resolution',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
