# Generated by Django 2.1.5 on 2019-02-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20190209_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(default=None, to='movie.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='homepage',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='preview',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
