# Generated by Django 2.1.5 on 2019-02-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20190209_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='filename',
            field=models.CharField(default='', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(default='', to='movie.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='homepage',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_movie_url',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='preview',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='resolution',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='', max_length=256),
        ),
    ]
