# Generated by Django 2.1.5 on 2019-02-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20190209_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='filename',
            field=models.CharField(blank=True, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='movie.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='homepage',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_movie_url',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='movie',
            name='preview',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='resolution',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
