# Generated by Django 2.1.5 on 2019-02-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20190209_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
