# Generated by Django 2.1.5 on 2019-02-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_auto_20190209_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='filename',
            field=models.CharField(default='', max_length=256, unique=True),
        ),
    ]
