# Generated by Django 2.1.5 on 2019-02-09 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_auto_20190209_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='preview',
        ),
    ]
