# Generated by Django 2.1.5 on 2019-02-09 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_auto_20190209_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
