# Generated by Django 2.2 on 2020-03-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_movie_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
